title: ComputerElite's blog
author: ComputerElite
description: Guess this guy does some development

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/ComputerElite3
      icon: twitter-square
      color: cyan
    - url: https://www.twitch.tv/computerelite_dev
      icon: twitch
      color: purple
    - url: https://www.youtube.com/channel/UC5-nODCcHg7ptaLJ9mrd72g
      icon: youtube
      color: red
    - url: https://github.com/computerelite
      icon: github-square
      color: yellow
      
  avatar_source: local
  avatar_path: /assets/CE_512px.png
# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
