on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "raw"
      - run: cd raw
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          target_branch: gh-pages
      - run: cd ..
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: "build"
      - run: cd build
      - name: Replace relative paths with absolute paths
        run: |
          find build -type f \( -name "*.html" -o -name "*.css" \) -print0 | while IFS= read -r -d '' file; do
            sed -i 's/src="\/\([0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}\/[^"]*\)"/src="\/blog\/\1"/g' "$file"
            sed -i 's/href="\/\([^"]*\)"/href="\/blog\/\1"/g' "$file"
            sed -i 's/src="\/assets\/\([^"]*\)"/src="\/blog\/assets\/\1"/g' "$file"
            sed -i 's/href="\/assets\/\([^"]*\)"/href="\/blog\/assets\/\1"/g' "$file"
            sed -i 's/url\(\"\/assets\/([^"]*)\"\)/url("\/blog\/assets\/\1")/g' "$file"
          done


      - name: Commit changes
        working-directory: ./build
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replace relative paths with absolute paths"
          git branch deploy
          git push --force origin deploy
