name: Replace Paths

on:
  push:
    branches:
      - gh-pages

jobs:
  replace-paths:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace relative paths with absolute paths
        run: |
          find . -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
            sed -i 's/src="\/\([0-9]\{4\}\/[0-9]\{2\}\/[0-9]\{2\}\/[^"]*\)"/src="\/blog\/\1"/g' "$file"
            sed -i 's/href="\/\([^"]*\)"/href="\/blog\/\1"/g' "$file"
            sed -i 's/src="\/assets\/\([^"]*\)"/src="\/blog\/assets\/\1"/g' "$file"
            sed -i 's/href="\/assets\/\([^"]*\)"/href="\/blog\/assets\/\1"/g' "$file"
          done
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replace relative paths with absolute paths"   
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy